sudo: required

os:
  - linux

language: go

services:
  - docker

go:
  - 1.9.2

script:
  - docker --version
  - go test -v ./... -cover
  - if [[ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]]; then
      export AWS_ACCESS_KEY_ID=${KOPS_ACCESS_KEY_ID};
      export AWS_SECRET_ACCESS_KEY=${KOPS_SECRET_ACCESS_KEY};
      pip install --user awscli;
      export PATH=$PATH:$HOME/.local/bin;
      aws --version;
      eval $(aws ecr get-login --region ap-northeast-1);
      export IMAGE=authd:${TRAVIS_TAG};
      if [[ $TRAVIS_TAG == *"dev"* ]]; then
        make authdd;
      else
        make authdp;
      fi;
      docker tag ${IMAGE} ${ECR_REPO_URI}/${IMAGE};
      docker images;
      docker push ${ECR_REPO_URI}/${IMAGE};
    else
      make;
    fi
