apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: authd
spec:
  selector:
    matchLabels:
      app: authd
  replicas: 1
  template:
    metadata:
      labels:
        app: authd
    spec:
      containers:
      - name: authd
        image: 963826138034.dkr.ecr.ap-northeast-1.amazonaws.com/authd:dev
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: Always
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8080
